### ISSUE TITLE
ibm errors

### ISSUE THREAD

**Issue by jrpool** [cvs-health/testaro#14]
Commentators report errors in the `ibm` test. These should be investigated and, if confirmed, reported as issues to IBM. Reported errors include:

- wrongly claims no lang attribute on html element on aaatraq.com
- wrongly claims no skip link on aaatraq.com
- wrongly fails incl.ca on Rpt_Aria_ComplementaryRequiredLabel_Implicit, although page has no elements with role complementary

**Comment by poolcvs** [comment]
Retested and found no claim of missing `lang` attribute on `html` element at aaatraq.com.
Retested and found no claim of missing skip link at aaatraq.com.
Attempted to retest incl.ca, but it is unreachable.
No specified errors could be found on retesting.
