### ISSUE TITLE
aatt prevention

### ISSUE THREAD

**Issue by jrpool** [cvs-health/testaro#19]
The reasons for some hosts preventing the `aatt` test while other hosts allow it should be investigated. If this is diagnosed and if the cause appears to be a deficiency in AATT, the issue should be reported to PayPal.

Preventions take 2 forms:

- timeout
- JSON format violation (e.g., truncation)

Examples of timeout hosts:

- www.cvs.com
- www.target.com
- www.riteaid.com
- www.amazon.com
- www.bartelldrugs.com
- www.nra.org (allowed on second try)

Examples of JSON-violating hosts:

- www.walgreens.com

Examples of allowing hosts:

- [jpdev.pro/site/index.html](jpdev.pro/site/index.html)
- www.irs.gov
- www.apple.com
- www.microsoft.com/en-us/?ql=3
- www.safeway.com
- www.aetna.com
- www.tesla.com
- www.whitehouse.gov
- www.senate.gov
- www.harvard.edu
- www.express-scripts.com
- www.hrw.org
- www.everytown.org
- www.democrats.org
- www.gop.com
- www.gp.org

**Comment by jrpool** [comment]
This phenomenon mostly holds when the browser type is changed from chromium to webkit or firefox.

**Comment by jrpool** [comment]
One way to investigate this issue is to run HTML CodeSniffer via Pa11y or directly.

**Comment by poolcvs** [comment]
AATT has been removed from Testaro and replaced with the `htmlcs` tool.
