### ISSUE TITLE
Running the hello world example on the README.md produces the same output as input with "bad job creation time"

### ISSUE THREAD

**Issue by vangj** [cvs-health/testaro#33]
I have a JSON file placed in `./jobdir/todo/be76p.json`.

```json
{
  "id": "be76p-ts25-w3c",
  "what": "Test W3C with 2 alfa rules",
  "strict": true,
  "timeLimit": 65,
  "acts": [
    {
      "type": "launch",
      "which": "chromium",
      "url": "https://www.w3c.org",
      "what": "Chromium browser"
    },
    {
      "type": "test",
      "which": "alfa",
      "what": "Siteimprove alfa tool",
      "rules": [
        "r25",
        "r71"
      ]
    }
  ],
  "sources": {
    "script": "tp25",
    "batch": "weborgs",
    "target": {
      "id": "w3c",
      "which": "https://www.w3c.org",
      "what": "World Wide Web Consortium"
    },
    "requester": "user@domain.org"
  },
  "jobCreationTime": "2023-11-14T12:01",
  "timeStamp": "be76p"
}
```

When I run the following command, the output is the same as the input. The exact command I run is as follows.

```bash
JOBDIR=./jobdir \
    REPORTDIR=./reportdir \
    DEBUG=true \
    node call run be76p
```

The console output is as follows. I do notice the `bad job creation time` output. What do I need to set this to?

```bash
bad job creation time
Job completed and report be76p-ts25-w3c.json saved in ./reportdir/raw
Execution completed
```

The `./report/raw/be76p.json` output is the same as the input. Also, the original file is moved from `./jobdir/todo/be76p.json` to `./jobdir/done/be76p.json`. 

What am I doing wrong?

**Comment by poolcvs** [comment]
Thank you, @vangj, for reporting this error, and I apologize for the delayed response. The README file states that the creation-time property in a job is named `creationTime`. But the example contained the incorrect (obsolete) name `jobCreationTime`. The `isValidReport` function in the `run` module checks job validity and complains about a missing `creationTime` property if the property does not have that name. Version 32.0.11 has now been published with the README example corrected.
