### ISSUE TITLE
Invalid Act

### ISSUE THREAD

**Issue by TathagataRoy1278** [cvs-health/testaro#40]
Hello.

I am trying to run some acts by calling the `node call run` command.

However for certain rulesets like axe, qualWeb and testaro are not running and report 

```
ERROR: Invalid act:
{
  "type": "test",
  "which": "testaro",
  "what": "Testaro tool"
}
```

The full file is as below.

```
{
 "id": "test1234",
 "what": "Test W3C with 2 alfa rules",
 "strict": true,
 "timeLimit": 65,
 "acts": [
{
      "type": "launch",
      "which": "chromium",
      "url": "https://www.example.com/",
      "what": "Chromium browser"
    },
    {
      "type": "test",
      "which": "aslint"
    },
    {
      "type": "test",
      "which": "alfa"
    },    
    {
      "type": "test",
      "which": "ed11y"
    },
    {
      "type": "test",
      "which": "htmlcs"
    },
    {
      "type": "test",
      "which": "nuVal"
    },
    {
      "type": "test",
      "which": "testaro",
      "what": "Testaro tool"
    }
  ],
 "sources": {
    "script": "tp99",
    "batch": "webOrgs",
    "lastTarget": false,
    "target": {
      "id": "w3c",
      "what": "World Wide Web Consortium",
      "which": "https://oxygena11y.wpengine.com/"
    },
    "requester": "user@domain.org"
 },
 "standard": "only",
 "observe": false,
 "timeStamp": "241208T1200",
 "creationTimeStamp": "241114T0328",
 "sendReportTo": "https://localhost:3004/testapp/api/report",
 "mergeID": "Q9"
}

```

Am I doing something wrong?
Thank you!

**Comment by poolcvs** [comment]
Thank you for posting this issue, @TathagataRoy1278.

The `run` module checks acts against the `actSpecs.js` file to determine whether acts are valid. For example, a `test` act running tests of the `testaro` tool is checked against the requirements in the `tools.testaro` property. There, two act properties are mandatory: `withItems` and `stopOnFail`. So, a `test` act for `testaro` must have those two properties. There is a third property, `args`, but it is not mandatory. I am assuming that this answer satisfactorily addresses the issue, but please comment further if not.

**Comment by TathagataRoy1278** [comment]
Ahh, thank you so much!
